version: '3'

services:

  opaca-bpmn-editor:
    build: opaca-bpmn-editor
    image: opaca-bpmn-modeller
    ports:
      - "8080:8080"
    depends_on:
      - promoai-api-server
    environment:
      LLM_BACKEND: http://localhost:5000

  promoai-api-server:
    build: promoai-api-server
    image: opaca-bpmn-modeller-llm-backend
    ports:
      - "5000:5000"
    environment:
      LLM_NAME: gpt-4o
      LLM_API_KEY: $OPENAI_API_KEY